// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ollamaUrl": string;
      "apiType": string;
      "openaiApiKey": string;
      "anthropicApiKey": string;
      "codexPath": string;
      "codexModel": string;
      "codexReasoning": string;
      "cloudConsent": boolean;
      "cloudContextTokens": number;
      "maxOutputTokens": number;
      "numCtx": number;
      "skimModel": string;
      "tldrModel": string;
      "enableSkim": boolean;
      "enableCitationCards": boolean;
      "s2Metadata": boolean;
      "highlightDensity": number;
      "highlightOpacity": number;
      "showFlags": boolean;
      "labelMode": string;
      "customLabels": string;
      "hiddenLabels": string;
    };
  }
}
