// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ollamaUrl": string;
      "apiType": string;
      "openaiCompatibleKey": string;
      "codexPath": string;
      "codexModel": string;
      "codexReasoning": string;
      "claudeModel": string;
      "claudePath": string;
      "cloudConsent": boolean;
      "contextTokens": number;
      "ollamaNumCtx": number;
      "skimModel": string;
      "tldrModel": string;
      "tldrWithSkim": boolean;
      "balancedCoverage": boolean;
      "highlightDensity": number;
      "highlightOpacity": number;
      "showFlags": boolean;
      "labelMode": string;
      "customLabels": string;
      "hiddenLabels": string;
    };
  }
}
